/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
  // mySidebar: [
  //   {
  //     type: 'doc',
  //     id: 'intro'
  //   },
  //   {
  //     type: 'doc',
  //     id: 'DesignDiagram',
  //   },
  //   {
  //     type: 'category',
  //     label: 'User Interfaces',
  //     collapsible: true,
  //     collapsed: false,
  //     items: [
  //       {
  //         type: 'doc',
  //         label: 'Introduction',
  //         id: 'User Interfaces/introduction',
  //       },
  //       {
  //         type: 'doc',
  //         id: 'User Interfaces/script-cmds',
  //       },
  //       {
  //         type: 'doc',
  //         id: 'User Interfaces/efs',
  //       },
  //       {
  //         type: 'doc',
  //         id: 'User Interfaces/ddl',
  //       },
  //       {
  //         type: 'doc',
  //         id: 'User Interfaces/dml',
  //       },

  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: 'XFS Interface',
  //     collapsible: true,
  //     collapsed: false,
  //     items: [
  //       {
  //         type: 'doc',
  //         label: 'Introduction',
  //         id: 'XfS Interface/introduction',
  //       },
  //       {
  //         type: 'doc',
  //         id: 'XfS Interface/Installation Guidelines',
  //       },
  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: 'Frontend User Interface',
  //     collapsible: true,
  //     collapsed: false,
  //     items: [
  //       {
  //         type: 'doc',
  //         label: 'Introduction',
  //         id: 'Frontend User Interface/introduction',
  //       },
  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: 'Frontend Programming Interface',
  //     collapsible: true,
  //     collapsed: false,
  //     items: [
  //       {
  //         type: 'doc',
  //         label: 'Introduction',
  //         id: 'Frontend Programming Interface/introduction',
  //       },
  //       {
  //         type: 'doc',
  //         id: 'Frontend Programming Interface/ddl',
  //       },
  //       {
  //         type: 'doc',
  //         id: 'Frontend Programming Interface/dml',
  //       },
  //     ],
  //   },
  //   // {
  //   //   type: 'link',
  //   //   label: 'Learn more',
  //   //   href: 'https://example.com',
  //   // },
  // ],

 Design: [
   {
     type: 'autogenerated', 
     dirName: 'Design'
    }
  ],
  XFS: [
    {
      type: 'autogenerated', 
      dirName: 'XFS Interface'
     }
   ],

};

module.exports = sidebars;
